using System;
using System.Collections.Generic;
using System.IO;
using System.Text;
using DistributedRecorder.Shared;
using UnityEngine;

namespace DistributedRecorder.Master
{
    /// <summary>
    /// Reads/writes <see cref="JobManifest"/> files and validates untrusted manifest content
    /// before it reaches the dispatch pipeline (lightweight-master-manifest, plan.md 案A).
    ///
    /// Security design: a manifest is a local file, but it is treated as untrusted input
    /// (plan.md 非機能要件) because it may be hand-edited or produced by a different machine.
    /// Every job-level field is re-validated with the SAME <see cref="InputValidator"/> that
    /// gates network-received <see cref="JobRequest"/> data on the Worker — no new validation
    /// logic is invented here (plan.md E2).
    ///
    /// Pure logic — no dependency on any <c>Unity.MultiTimelineRecorder</c> type or any
    /// <c>UnityEditor</c> UI API (dialogs are shown by the caller) — so it is directly
    /// exercisable from hermetic EditMode tests.
    /// </summary>
    public static class JobManifestIO
    {
        /// <summary>Only schema version currently accepted by <see cref="TryLoad"/> (plan.md E1).</summary>
        public const int CurrentSchemaVersion = 1;

        /// <summary>Maximum number of jobs accepted in a single manifest (plan.md B2, DoS guard).</summary>
        public const int MaxJobCount = 1000;

        /// <summary>Maximum manifest file size in bytes (plan.md B4, DoS guard).</summary>
        public const long MaxManifestFileSizeBytes = 8L * 1024 * 1024; // 8 MB

        // Placeholder values used only to satisfy InputValidator.Validate's structural
        // requirements for fields that are re-generated by the Master at ACTUAL dispatch time
        // (masterUnityVersion / masterRecorderVersion are overwritten by
        // JobDispatcher.DispatchAsync regardless of what a probe request carries; projectHash
        // is only consulted on the non-git fallback path — see ValidateEntry). Using fixed
        // values keeps validation deterministic and hermetic (no live PackageManager or git
        // queries during manifest load).
        private const string PlaceholderVersion = "0.0.0";
        private static readonly string PlaceholderProjectHash = new string('0', 64);

        /// <summary>
        /// Serializes <paramref name="manifest"/> to <paramref name="path"/> as pretty-printed
        /// UTF-8 JSON (no BOM).
        /// </summary>
        public static bool TrySave(string path, JobManifest manifest, out string error)
        {
            error = string.Empty;

            if (string.IsNullOrEmpty(path))
            {
                error = "path is null or empty.";
                return false;
            }
            if (manifest == null)
            {
                error = "manifest is null.";
                return false;
            }

            try
            {
                string json = JsonUtility.ToJson(manifest, prettyPrint: true);
                File.WriteAllText(path, json, new UTF8Encoding(encoderShouldEmitUTF8Identifier: false));
                return true;
            }
            catch (Exception ex)
            {
                error = $"Failed to write manifest to '{path}': {ex.Message}";
                return false;
            }
        }

        /// <summary>
        /// Loads and validates a manifest from <paramref name="path"/>.
        ///
        /// Validation order (fail-fast for structural problems, then per-job filtering):
        ///  1. File existence + size cap (<see cref="MaxManifestFileSizeBytes"/>) — plan.md B4.
        ///  2. JSON parse.
        ///  3. <see cref="JobManifest.schemaVersion"/> must equal
        ///     <see cref="CurrentSchemaVersion"/> exactly — plan.md E1 (no migration is
        ///     implemented; unknown/newer AND older-than-supported values are both rejected).
        ///  4. <see cref="JobManifest.sourceGitCommit"/>, when non-empty, must be a
        ///     syntactically valid commit SHA — checked once at the header level so a malformed
        ///     header does not produce a misleading "every job rejected" result.
        ///  5. Job count cap (<see cref="MaxJobCount"/>) — plan.md B2.
        ///  6. Per-job field validation via <see cref="InputValidator"/> (reused, not
        ///     reimplemented) — plan.md E2. Individual invalid jobs are dropped and reported
        ///     via <paramref name="jobWarnings"/>; the batch as a whole still loads
        ///     successfully (including the degenerate empty-jobs case — plan.md B1).
        /// </summary>
        /// <param name="path">Absolute path to the <c>.mtrjob.json</c> manifest file.</param>
        /// <param name="manifest">On success: the loaded manifest with only valid jobs retained.</param>
        /// <param name="jobWarnings">Human-readable reasons for any job entries that were dropped.</param>
        /// <param name="error">Fatal error message when returning <c>false</c>.</param>
        public static bool TryLoad(
            string path, out JobManifest manifest, out List<string> jobWarnings, out string error)
        {
            manifest    = null;
            jobWarnings = new List<string>();
            error       = string.Empty;

            if (string.IsNullOrEmpty(path))
            {
                error = "path is null or empty.";
                return false;
            }

            if (!File.Exists(path))
            {
                error = $"Manifest file not found: {path}";
                return false;
            }

            long fileLength;
            try
            {
                fileLength = new FileInfo(path).Length;
            }
            catch (Exception ex)
            {
                error = $"Failed to stat manifest file: {ex.Message}";
                return false;
            }

            if (fileLength > MaxManifestFileSizeBytes)
            {
                error = $"Manifest file is {fileLength} bytes, exceeding the " +
                        $"{MaxManifestFileSizeBytes / (1024 * 1024)} MB limit.";
                return false;
            }

            string json;
            try
            {
                json = File.ReadAllText(path, Encoding.UTF8);
            }
            catch (Exception ex)
            {
                error = $"Failed to read manifest file: {ex.Message}";
                return false;
            }

            JobManifest loaded;
            try
            {
                loaded = JsonUtility.FromJson<JobManifest>(json);
            }
            catch (Exception ex)
            {
                error = $"Manifest is not valid JSON: {ex.Message}";
                return false;
            }

            if (loaded == null)
            {
                error = "Manifest could not be parsed (empty or malformed JSON).";
                return false;
            }

            if (loaded.schemaVersion != CurrentSchemaVersion)
            {
                error = $"Unsupported manifest schemaVersion {loaded.schemaVersion} " +
                        $"(this tool supports version {CurrentSchemaVersion} only). " +
                        "Re-export the manifest with a compatible tool version.";
                return false;
            }

            if (!string.IsNullOrEmpty(loaded.sourceGitCommit) &&
                !InputValidator.IsValidGitCommitSha(loaded.sourceGitCommit))
            {
                error = $"Manifest sourceGitCommit is not a valid git commit SHA: '{loaded.sourceGitCommit}'.";
                return false;
            }

            if (loaded.jobs == null)
                loaded.jobs = new List<JobManifestEntry>();

            if (loaded.jobs.Count > MaxJobCount)
            {
                error = $"Manifest contains {loaded.jobs.Count} jobs, exceeding the " +
                        $"{MaxJobCount}-job limit.";
                return false;
            }

            var validJobs = new List<JobManifestEntry>(loaded.jobs.Count);
            for (int i = 0; i < loaded.jobs.Count; i++)
            {
                var entry = loaded.jobs[i];
                if (entry != null && ValidateEntry(entry, loaded.sourceGitCommit, out string reason))
                {
                    validJobs.Add(entry);
                }
                else
                {
                    string label = string.IsNullOrEmpty(entry?.DirectorObjectName)
                        ? $"index {i}"
                        : $"'{entry.DirectorObjectName}' (index {i})";
                    jobWarnings.Add($"Job {label} rejected: {(entry == null ? "entry is null" : reason)}");
                }
            }
            loaded.jobs = validJobs;

            manifest = loaded;
            return true;
        }

        /// <summary>
        /// Validates a single manifest job entry by reconstructing the equivalent
        /// <see cref="JobRequest"/> it would produce at dispatch time and running it through
        /// the existing <see cref="InputValidator.Validate"/> (plan.md E2 — reuse, not
        /// reimplement: path traversal, length caps, enum whitelists, RT-GUID / gitCommit hex
        /// format are all inherited from that single source of truth).
        ///
        /// <paramref name="sourceGitCommit"/> is injected as the probe's <c>gitCommit</c>
        /// because that is exactly what the lightweight dispatch path (<c>JobDispatcher</c>
        /// commit override, plan.md 論点4 機構A) sends over the wire for every job in the batch.
        ///
        /// jobId / masterUnityVersion / masterRecorderVersion / projectHash use fixed
        /// placeholders: the real values are generated fresh by the Master at actual dispatch
        /// time and are irrelevant to whether THIS entry's own fields are well-formed.
        /// </summary>
        internal static bool ValidateEntry(JobManifestEntry entry, string sourceGitCommit, out string reason)
        {
            reason = string.Empty;
            if (entry == null)
            {
                reason = "Job entry is null.";
                return false;
            }

            bool hasGitCommit = !string.IsNullOrEmpty(sourceGitCommit);

            var probe = new JobRequest
            {
                jobId                      = "manifest-preview",
                scenePath                  = entry.ScenePath ?? string.Empty,
                timelineAssetPath          = entry.TimelineAssetPath ?? string.Empty,
                directorObjectName         = entry.DirectorObjectName ?? string.Empty,
                directorHierarchyPath      = entry.DirectorHierarchyPath ?? string.Empty,
                recorderConfig             = entry.JobConfig,
                recorderConfigJson         = entry.RecorderConfigJson ?? string.Empty,
                jobScopeHash               = entry.JobScopeHash ?? string.Empty,
                targetCameraHierarchyPath  = entry.TargetCameraHierarchyPath ?? string.Empty,
                targetCameraName           = entry.TargetCameraName ?? string.Empty,
                renderTextureGuid          = entry.RenderTextureGuid ?? string.Empty,
                effectiveWidth             = entry.EffectiveWidth,
                effectiveHeight            = entry.EffectiveHeight,
                effectiveFrameRate         = entry.EffectiveFrameRate,
                resolvedOutputRelativePath = entry.ResolvedOutputRelativePath ?? string.Empty,
                gitCommit                  = sourceGitCommit ?? string.Empty,
                projectHash                = hasGitCommit ? string.Empty : PlaceholderProjectHash,
                masterUnityVersion         = PlaceholderVersion,
                masterRecorderVersion      = PlaceholderVersion,
            };

            return InputValidator.Validate(probe, out reason);
        }
    }
}
